kind: pipeline
name: default

steps:
- name: build
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#steps:
#- name: build-java-app
#  image: docker.io/kameshsampath/drone-java-maven-plugin:v1.0.0
#  pull: if-not-exists

- name: docker  
  image: plugins/acr
  settings:
    registry: dronecr.azurecr.io
    service_principal_client_id: dronecr
    service_principal_client_secret: T0AhF5uDJfQXia0jDRe12jKAud2ABLXxUGXbdMPxMc+ACRBtR7Ko
    repo: drone/poc
