kind: pipeline
name: default
type: docker

steps:
- name: build
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

- name: Az Login
  image: mcr.microsoft.com/azure-cli
  pull: if-not-exists
  environment:
    AZURE_APPLICATION_ID: 'f562782f-f00d-40bf-b4c8-88a3af4f3090'
    AZURE_SECRET: 'k318Q~O.A~0h5lvwWznfHKTeZW6s-oVq-kgvtaFM'
    AZURE_TENANT_ID: '58890a1b-1e36-4669-b0e5-71d700ffad22'
  commands:
    - az login --service-principal -u $AZURE_APPLICATION_ID -p $AZURE_SECRET --tenant $AZURE_TENANT_ID
    - az acr login -n dronecr --expose-token
    - az account set --subscription bb329e6f-49f4-437c-9bad-544bb2b63a12
    - az aks get-credentials --resource-group drone-rg --name aks-drone
    - echo "Aquí va el kubectl apply"
  
- name: docker
  image: docker
  commands:
    - docker push dronecr.azurecr.io/spring-elasticsearch-client
